
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kang L
 */
public class KalkulatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorFrame
     */
    private Kalkulator kalkulator;
    
    public KalkulatorFrame() {
        initComponents();
        kalkulator = new Kalkulator();
        
        tambahButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double a = Double.parseDouble(nomor1TextField.getText());
                double b = Double.parseDouble(nomor2TextField.getText());
                kalkulator.tambah(a, b);
                hasilTextField.setText(String.valueOf(kalkulator.getResult()));
            }
        });
        
        kurangButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double a = Double.parseDouble(nomor1TextField.getText());
                double b = Double.parseDouble(nomor2TextField.getText());
                kalkulator.kurang(a, b);
                hasilTextField.setText(String.valueOf(kalkulator.getResult()));
            }
        });
        
        kaliButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double a = Double.parseDouble(nomor1TextField.getText());
                double b = Double.parseDouble(nomor2TextField.getText());
                kalkulator.kali(a, b);
                hasilTextField.setText(String.valueOf(kalkulator.getResult()));
            }
        });
        
        bagiButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double a = Double.parseDouble(nomor1TextField.getText());
                double b = Double.parseDouble(nomor2TextField.getText());
                kalkulator.bagi(a, b);
                hasilTextField.setText(String.valueOf(kalkulator.getResult()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kalkulatorsederhanaLabel = new javax.swing.JLabel();
        bilangan1Label1 = new javax.swing.JLabel();
        nomor1TextField = new javax.swing.JTextField();
        bilangan1Label2 = new javax.swing.JLabel();
        nomor2TextField = new javax.swing.JTextField();
        tambahButton = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        bagiButton = new javax.swing.JButton();
        hasilTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kalkulatorsederhanaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kalkulatorsederhanaLabel.setText("Kalkulator Sederhana");

        bilangan1Label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bilangan1Label1.setText("Bilangan 1");

        bilangan1Label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bilangan1Label2.setText("Bilangan 2");

        tambahButton.setText("Tambah");

        kurangButton.setText("Kurang");

        kaliButton.setText("Kali");

        bagiButton.setText("Bagi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kalkulatorsederhanaLabel)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahButton)
                        .addGap(18, 18, 18)
                        .addComponent(kurangButton)
                        .addGap(18, 18, 18)
                        .addComponent(kaliButton)
                        .addGap(18, 18, 18)
                        .addComponent(bagiButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bilangan1Label2)
                            .addGap(18, 18, 18)
                            .addComponent(nomor2TextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bilangan1Label1)
                            .addGap(18, 18, 18)
                            .addComponent(nomor1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(kalkulatorsederhanaLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilangan1Label1)
                    .addComponent(nomor1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilangan1Label2)
                    .addComponent(nomor2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton)
                    .addComponent(kurangButton)
                    .addComponent(kaliButton)
                    .addComponent(bagiButton))
                .addGap(18, 18, 18)
                .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagiButton;
    private javax.swing.JLabel bilangan1Label1;
    private javax.swing.JLabel bilangan1Label2;
    private javax.swing.JTextField hasilTextField;
    private javax.swing.JButton kaliButton;
    private javax.swing.JLabel kalkulatorsederhanaLabel;
    private javax.swing.JButton kurangButton;
    private javax.swing.JTextField nomor1TextField;
    private javax.swing.JTextField nomor2TextField;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
